{
 "title": "Dev.DashBoard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PHP Log",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{compose_service=\"php\"}"
    }
   ]
  },
  {
   "title": "NGINX Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{compose_service=\"nginx\"}"
    }
   ]
  },
  {
   "title": "MailDev Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{compose_service=\"maildev\"}"
    }
   ]
  },
  {
   "title": "Node.js Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{compose_service=\"nodejs\"}"
    }
   ]
  }
 ]
}