{
 "title": "WebDevLogs",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "PHP Log",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{compose_service=\"php\"}"
    }
   ]
  },
  {
   "title": "Node.js Log",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{compose_service=\"nodejs\"}"
    }
   ]
  },
  {
   "title": "NGINX Log",
   "type": "logs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{compose_service=\"nginx\"}"
    }
   ]
  },
  {
   "title": "MailDev Log",
   "type": "logs",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{compose_service=\"maildev\"}"
    }
   ]
  },
  {
   "title": "Adminer Log",
   "type": "logs",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "{compose_service=\"adminer\"}"
    }
   ]
  },
  {
   "title": "Gitea Log",
   "type": "logs",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 15 },
   "targets": [
    {
     "expr": "{compose_service=\"gitea\"}"
    }
   ]
  }
 ]
}